// Default stack logos offered in the admin skill form (served by the devicon CDN).
export const DEVICON_BASE = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons";

export interface SkillPreset {
    name: string;
    category: string;
    color: string;
    logo: string;
}

export const SKILL_CATEGORIES = [
    "Frontend", "Backend", "Fullstack", "Mobile", "Desktop", "Language",
    "Database", "DevOps", "Cloud", "Tooling", "Testing", "Design",
];

export const SKILL_PRESETS: SkillPreset[] = [
    { name: "React", category: "Frontend", color: "#61DAFB", logo: `${DEVICON_BASE}/react/react-original.svg` },
    { name: "Next.js", category: "Fullstack", color: "#ffffff", logo: `${DEVICON_BASE}/nextjs/nextjs-original.svg` },
    { name: "Angular", category: "Frontend", color: "#DD0031", logo: `${DEVICON_BASE}/angular/angular-original.svg` },
    { name: "Vue.js", category: "Frontend", color: "#4FC08D", logo: `${DEVICON_BASE}/vuejs/vuejs-original.svg` },
    { name: "Nuxt", category: "Fullstack", color: "#00DC82", logo: `${DEVICON_BASE}/nuxtjs/nuxtjs-original.svg` },
    { name: "Svelte", category: "Frontend", color: "#FF3E00", logo: `${DEVICON_BASE}/svelte/svelte-original.svg` },
    { name: "TypeScript", category: "Language", color: "#3178C6", logo: `${DEVICON_BASE}/typescript/typescript-original.svg` },
    { name: "JavaScript", category: "Language", color: "#F7DF1E", logo: `${DEVICON_BASE}/javascript/javascript-original.svg` },
    { name: "HTML5", category: "Frontend", color: "#E34F26", logo: `${DEVICON_BASE}/html5/html5-original.svg` },
    { name: "CSS3", category: "Frontend", color: "#1572B6", logo: `${DEVICON_BASE}/css3/css3-original.svg` },
    { name: "Sass", category: "Frontend", color: "#CC6699", logo: `${DEVICON_BASE}/sass/sass-original.svg` },
    { name: "Tailwind CSS", category: "Frontend", color: "#06B6D4", logo: `${DEVICON_BASE}/tailwindcss/tailwindcss-original.svg` },
    { name: "Bootstrap", category: "Frontend", color: "#7952B3", logo: `${DEVICON_BASE}/bootstrap/bootstrap-original.svg` },
    { name: "jQuery", category: "Frontend", color: "#0769AD", logo: `${DEVICON_BASE}/jquery/jquery-original.svg` },
    { name: "Redux", category: "Frontend", color: "#764ABC", logo: `${DEVICON_BASE}/redux/redux-original.svg` },
    { name: "Vite", category: "Tooling", color: "#646CFF", logo: `${DEVICON_BASE}/vitejs/vitejs-original.svg` },
    { name: "Webpack", category: "Tooling", color: "#8DD6F9", logo: `${DEVICON_BASE}/webpack/webpack-original.svg` },
    { name: "Three.js", category: "Frontend", color: "#ffffff", logo: `${DEVICON_BASE}/threejs/threejs-original.svg` },
    { name: "D3.js", category: "Frontend", color: "#F9A03C", logo: `${DEVICON_BASE}/d3js/d3js-original.svg` },
    { name: "Storybook", category: "Tooling", color: "#FF4785", logo: `${DEVICON_BASE}/storybook/storybook-original.svg` },
    { name: "Node.js", category: "Backend", color: "#339933", logo: `${DEVICON_BASE}/nodejs/nodejs-original.svg` },
    { name: "Express", category: "Backend", color: "#ffffff", logo: `${DEVICON_BASE}/express/express-original.svg` },
    { name: "NestJS", category: "Backend", color: "#E0234E", logo: `${DEVICON_BASE}/nestjs/nestjs-original.svg` },
    { name: ".NET", category: "Backend", color: "#512BD4", logo: `${DEVICON_BASE}/dotnetcore/dotnetcore-original.svg` },
    { name: "C#", category: "Language", color: "#9B4F96", logo: `${DEVICON_BASE}/csharp/csharp-original.svg` },
    { name: "Python", category: "Language", color: "#3776AB", logo: `${DEVICON_BASE}/python/python-original.svg` },
    { name: "Django", category: "Backend", color: "#092E20", logo: `${DEVICON_BASE}/django/django-plain.svg` },
    { name: "FastAPI", category: "Backend", color: "#009688", logo: `${DEVICON_BASE}/fastapi/fastapi-original.svg` },
    { name: "Flask", category: "Backend", color: "#ffffff", logo: `${DEVICON_BASE}/flask/flask-original.svg` },
    { name: "Java", category: "Language", color: "#ED8B00", logo: `${DEVICON_BASE}/java/java-original.svg` },
    { name: "Spring", category: "Backend", color: "#6DB33F", logo: `${DEVICON_BASE}/spring/spring-original.svg` },
    { name: "Kotlin", category: "Language", color: "#7F52FF", logo: `${DEVICON_BASE}/kotlin/kotlin-original.svg` },
    { name: "Go", category: "Language", color: "#00ADD8", logo: `${DEVICON_BASE}/go/go-original.svg` },
    { name: "Rust", category: "Language", color: "#DEA584", logo: `${DEVICON_BASE}/rust/rust-original.svg` },
    { name: "PHP", category: "Language", color: "#777BB4", logo: `${DEVICON_BASE}/php/php-original.svg` },
    { name: "Laravel", category: "Backend", color: "#FF2D20", logo: `${DEVICON_BASE}/laravel/laravel-original.svg` },
    { name: "Symfony", category: "Backend", color: "#ffffff", logo: `${DEVICON_BASE}/symfony/symfony-original.svg` },
    { name: "Ruby", category: "Language", color: "#CC342D", logo: `${DEVICON_BASE}/ruby/ruby-original.svg` },
    { name: "Rails", category: "Backend", color: "#CC0000", logo: `${DEVICON_BASE}/rails/rails-plain.svg` },
    { name: "C", category: "Language", color: "#A8B9CC", logo: `${DEVICON_BASE}/c/c-original.svg` },
    { name: "C++", category: "Language", color: "#00599C", logo: `${DEVICON_BASE}/cplusplus/cplusplus-original.svg` },
    { name: "GraphQL", category: "Backend", color: "#E10098", logo: `${DEVICON_BASE}/graphql/graphql-plain.svg` },
    { name: "Prisma", category: "Backend", color: "#5A67D8", logo: `${DEVICON_BASE}/prisma/prisma-original.svg` },
    { name: "Flutter", category: "Mobile", color: "#02569B", logo: `${DEVICON_BASE}/flutter/flutter-original.svg` },
    { name: "Dart", category: "Language", color: "#0175C2", logo: `${DEVICON_BASE}/dart/dart-original.svg` },
    { name: "Swift", category: "Mobile", color: "#F05138", logo: `${DEVICON_BASE}/swift/swift-original.svg` },
    { name: "Android", category: "Mobile", color: "#3DDC84", logo: `${DEVICON_BASE}/android/android-original.svg` },
    { name: "iOS", category: "Mobile", color: "#ffffff", logo: `${DEVICON_BASE}/apple/apple-original.svg` },
    { name: "Ionic", category: "Mobile", color: "#3880FF", logo: `${DEVICON_BASE}/ionic/ionic-original.svg` },
    { name: "Electron", category: "Desktop", color: "#47848F", logo: `${DEVICON_BASE}/electron/electron-original.svg` },
    { name: "PostgreSQL", category: "Database", color: "#4169E1", logo: `${DEVICON_BASE}/postgresql/postgresql-original.svg` },
    { name: "MySQL", category: "Database", color: "#4479A1", logo: `${DEVICON_BASE}/mysql/mysql-original.svg` },
    { name: "MongoDB", category: "Database", color: "#47A248", logo: `${DEVICON_BASE}/mongodb/mongodb-original.svg` },
    { name: "Redis", category: "Database", color: "#DC382D", logo: `${DEVICON_BASE}/redis/redis-original.svg` },
    { name: "SQLite", category: "Database", color: "#003B57", logo: `${DEVICON_BASE}/sqlite/sqlite-original.svg` },
    { name: "Supabase", category: "Database", color: "#3ECF8E", logo: `${DEVICON_BASE}/supabase/supabase-original.svg` },
    { name: "Firebase", category: "Database", color: "#FFCA28", logo: `${DEVICON_BASE}/firebase/firebase-original.svg` },
    { name: "Docker", category: "DevOps", color: "#2496ED", logo: `${DEVICON_BASE}/docker/docker-original.svg` },
    { name: "Kubernetes", category: "DevOps", color: "#326CE5", logo: `${DEVICON_BASE}/kubernetes/kubernetes-original.svg` },
    { name: "Git", category: "Tooling", color: "#F05032", logo: `${DEVICON_BASE}/git/git-original.svg` },
    { name: "GitHub", category: "Tooling", color: "#ffffff", logo: `${DEVICON_BASE}/github/github-original.svg` },
    { name: "GitLab", category: "Tooling", color: "#FC6D26", logo: `${DEVICON_BASE}/gitlab/gitlab-original.svg` },
    { name: "Linux", category: "DevOps", color: "#FCC624", logo: `${DEVICON_BASE}/linux/linux-original.svg` },
    { name: "Nginx", category: "DevOps", color: "#009639", logo: `${DEVICON_BASE}/nginx/nginx-original.svg` },
    { name: "AWS", category: "Cloud", color: "#FF9900", logo: `${DEVICON_BASE}/amazonwebservices/amazonwebservices-original-wordmark.svg` },
    { name: "Azure", category: "Cloud", color: "#0078D4", logo: `${DEVICON_BASE}/azure/azure-original.svg` },
    { name: "Google Cloud", category: "Cloud", color: "#4285F4", logo: `${DEVICON_BASE}/googlecloud/googlecloud-original.svg` },
    { name: "Vercel", category: "Cloud", color: "#ffffff", logo: `${DEVICON_BASE}/vercel/vercel-original.svg` },
    { name: "Figma", category: "Design", color: "#F24E1E", logo: `${DEVICON_BASE}/figma/figma-original.svg` },
    { name: "Jest", category: "Testing", color: "#C21325", logo: `${DEVICON_BASE}/jest/jest-plain.svg` },
    { name: "npm", category: "Tooling", color: "#CB3837", logo: `${DEVICON_BASE}/npm/npm-original-wordmark.svg` },
];
